### ISSUE TITLE
Local Serverless actions/commands failing:  Function "srcs-github-export" doesn't exist in this Service

### ISSUE THREAD

**Issue by neomatrix369** [julianghionoiu/dpnt-coverage#22]
### Command:

```
SLS_DEBUG=* serverless invoke local --function srcs-github-export --path src/test/resources/tdl/datapoint/coverage/sample_s3_via_sns_event.json
```

### Error:
Function "srcs-github-export" doesn't exist in this Service

### Stacktrace:
ServerlessError: Function "srcs-github-export" doesn't exist in this Service
    at Service.getFunction (/home/satyasai/.nvm/versions/node/v10.6.0/lib/node_modules/serverless/lib/classes/Service.js:232:11)
    at AwsInvokeLocal.extendedValidate (/home/satyasai/.nvm/versions/node/v10.6.0/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:50:56)
From previous event:
    at Object.invoke:local:invoke [as hook] (/home/satyasai/.nvm/versions/node/v10.6.0/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:24:10)
    at BbPromise.reduce (/home/satyasai/.nvm/versions/node/v10.6.0/lib/node_modules/serverless/lib/classes/PluginManager.js:390:55)
From previous event:
    at PluginManager.invoke (/home/satyasai/.nvm/versions/node/v10.6.0/lib/node_modules/serverless/lib/classes/PluginManager.js:390:22)
    at PluginManager.run (/home/satyasai/.nvm/versions/node/v10.6.0/lib/node_modules/serverless/lib/classes/PluginManager.js:421:17)
    at variables.populateService.then.then (/home/satyasai/.nvm/versions/node/v10.6.0/lib/node_modules/serverless/lib/Serverless.js:157:33)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Serverless.run (/home/satyasai/.nvm/versions/node/v10.6.0/lib/node_modules/serverless/lib/Serverless.js:144:8)
    at serverless.init.then (/home/satyasai/.nvm/versions/node/v10.6.0/lib/node_modules/serverless/bin/serverless:43:50)

**Comment by neomatrix369** [comment]
Possibly a mistake in the docs
