### ISSUE TITLE
Local Serverless actions/commands failing: config file not found

### ISSUE THREAD

**Issue by neomatrix369** [julianghionoiu/dpnt-coverage#23]
```bash
 serverless deploy --stage dev                                                                                                      
 ```

Output:

> Serverless Warning --------------------------------------
> 
>  A valid file to satisfy the declaration 'file(config/dev.params.yml)' could not be found.
> 

Stack trace:
```javascript
Stack Trace --------------------------------------------
 
ServerlessError: ServerlessError: AWS provider credentials not found. Learn how to set up AWS provider credentials in our docs here: <http://bit.ly/aws-creds-setup>.
    at AwsDeploy.BbPromise.bind.then.catch (/home/satyasai/.nvm/versions/node/v10.6.0/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/createStack.js:90:15)
From previous event:
    at AwsDeploy.createStack (/home/satyasai/.nvm/versions/node/v10.6.0/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/createStack.js:81:13)
From previous event:
    at Object.aws:deploy:deploy:createStack [as hook] (/home/satyasai/.nvm/versions/node/v10.6.0/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:102:10)
    at BbPromise.reduce (/home/satyasai/.nvm/versions/node/v10.6.0/lib/node_modules/serverless/lib/classes/PluginManager.js:390:55)
From previous event:
    at PluginManager.invoke (/home/satyasai/.nvm/versions/node/v10.6.0/lib/node_modules/serverless/lib/classes/PluginManager.js:390:22)
    at PluginManager.spawn (/home/satyasai/.nvm/versions/node/v10.6.0/lib/node_modules/serverless/lib/classes/PluginManager.js:408:17)
    at AwsDeploy.BbPromise.bind.then (/home/satyasai/.nvm/versions/node/v10.6.0/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:95:48)
From previous event:
    at Object.deploy:deploy [as hook] (/home/satyasai/.nvm/versions/node/v10.6.0/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:91:10)
    at BbPromise.reduce (/home/satyasai/.nvm/versions/node/v10.6.0/lib/node_modules/serverless/lib/classes/PluginManager.js:390:55)
From previous event:
    at PluginManager.invoke (/home/satyasai/.nvm/versions/node/v10.6.0/lib/node_modules/serverless/lib/classes/PluginManager.js:390:22)
    at PluginManager.run (/home/satyasai/.nvm/versions/node/v10.6.0/lib/node_modules/serverless/lib/classes/PluginManager.js:421:17)
    at variables.populateService.then.then (/home/satyasai/.nvm/versions/node/v10.6.0/lib/node_modules/serverless/lib/Serverless.js:157:33)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Serverless.run (/home/satyasai/.nvm/versions/node/v10.6.0/lib/node_modules/serverless/lib/Serverless.js:144:8)
    at serverless.init.then (/home/satyasai/.nvm/versions/node/v10.6.0/lib/node_modules/serverless/bin/serverless:43:50)
```

What should a sample `config/dev.params.yml` look like?

**Comment by neomatrix369** [comment]
@julianghionoiu Any hints here, I must be missing steps I think, also a sample config file will certainly help I'll look at the project to figure it out

**Comment by neomatrix369** [comment]
Resolved by copying existing param file, see README update
