### ISSUE TITLE
Local Serverless actions/commands failing: The specified bucket does not exist

### ISSUE THREAD

**Issue by neomatrix369** [julianghionoiu/dpnt-coverage#26]
### Startup

Ran all the three `local-xxxx` instances with the right param, followed by the test to verify the setup is right

```
$ serverless invoke local --function call-ecs-to-compute-coverage --path src/test/resources/tdl/datapoint/coverage/sample_s3_via_sns_event.json
```

### Output 
```java
 Serverless Warning --------------------------------------
 
  A valid undefined to satisfy the declaration 'deep:1.ECS_ACCOUNT_ID' could not be found.
 
Serverless: In order to get human-readable output, please implement "toString()" method of your "ApiGatewayResponse" object.
log4j:WARN No appenders could be found for logger (com.amazonaws.AmazonWebServiceClient).

log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

Aug 18, 2018 9:29:20 PM tdl.datapoint.coverage.CoverageUploadHandler handleRequest
INFO: {Records=[{Sns={Message={"Records":[{"s3":{"bucket":{"name":"tdl-test-auth"},"object":{"key":"TCH/user01/test1.srcs"}}}]}}}]}

Aug 18, 2018 9:29:20 PM tdl.datapoint.coverage.CoverageUploadHandler handleS3Event
INFO: Process S3 event with: S3BucketEvent{bucket='tdl-test-auth', key='TCH/user01/test1.srcs'}

Aug 18, 2018 9:29:20 PM tdl.datapoint.coverage.CoverageUploadHandler handleS3Event
INFO: Initialise local temp repo

21:29:20.106 [main] DEBUG org.eclipse.jgit.util.FS - readpipe [git, --version],/usr/bin

21:29:20.114 [main] DEBUG org.eclipse.jgit.util.FS - readpipe may return 'git version 2.17.0'

21:29:20.114 [main] DEBUG org.eclipse.jgit.util.FS - remaining output:

21:29:20.114 [main] DEBUG org.eclipse.jgit.util.FS - readpipe [git, config, --system, --edit],/usr/bin

21:29:20.116 [main] DEBUG org.eclipse.jgit.util.FS - readpipe may return '/etc/gitconfig'

21:29:20.116 [main] DEBUG org.eclipse.jgit.util.FS - remaining output:


Aug 18, 2018 9:29:20 PM tdl.datapoint.coverage.CoverageUploadHandler handleS3Event
INFO: Local repo initialised at /tmp/user019035827231843343119/.git

Aug 18, 2018 9:29:20 PM tdl.datapoint.coverage.CoverageUploadHandler handleS3Event
INFO: Read repo from SRCS file TCH/user01/test1.srcs

Aug 18, 2018 9:29:20 PM tdl.datapoint.coverage.CoverageUploadHandler handleRequest
SEVERE: The specified bucket does not exist (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket; Request ID: 3L137; S3 Extended Request ID: 3L137)
com.amazonaws.services.s3.model.AmazonS3Exception: The specified bucket does not exist (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket; Request ID: 3L137; S3 Extended Request ID: 3L137), S3 Extended Request ID: 3L137
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1632)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1058)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4325)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4272)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1409)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1270)
	at tdl.datapoint.coverage.CoverageUploadHandler.handleS3Event(CoverageUploadHandler.java:141)
	at tdl.datapoint.coverage.CoverageUploadHandler.handleRequest(CoverageUploadHandler.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.serverless.InvokeBridge.invoke(InvokeBridge.java:82)
	at com.serverless.InvokeBridge.<init>(InvokeBridge.java:36)
	at com.serverless.InvokeBridge.main(InvokeBridge.java:133)


java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.serverless.InvokeBridge.invoke(InvokeBridge.java:82)
	at com.serverless.InvokeBridge.<init>(InvokeBridge.java:36)
	at com.serverless.InvokeBridge.main(InvokeBridge.java:133)

Caused by: java.lang.RuntimeException: com.amazonaws.services.s3.model.AmazonS3Exception: The specified bucket does not exist (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket; Request ID: 3L137; S3 Extended Request ID: 3L137), S3 Extended Request ID: 3L137
	at tdl.datapoint.coverage.CoverageUploadHandler.handleRequest(CoverageUploadHandler.java:126)
	... 7 more

Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: The specified bucket does not exist (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket; Request ID: 3L137; S3 Extended Request ID: 3L137), S3 Extended Request ID: 3L137
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1632)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1058)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)

	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)

	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4325)

	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4272)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1409)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1270)

	at tdl.datapoint.coverage.CoverageUploadHandler.handleS3Event(CoverageUploadHandler.java:141)
	at tdl.datapoint.coverage.CoverageUploadHandler.handleRequest(CoverageUploadHandler.java:122)
	... 7 more
```

**Comment by neomatrix369** [comment]
I also tried amending the `sample_s3_via_sns_event.json`, with 

```
{
  "Records": [
    {
      "Sns": {
        "Message": "{\"Records\":[{\"s3\":{\"bucket\":{\"name\":\"localbucket\"},\"object\":{\"key\":\"TCH/952ef09fd5b1402389a2e6c0d3ea17fd/test1.srcs\"}}}]}"
      }
    }
  ]
}

```
but get the same error

**Comment by julianghionoiu** [comment]
Thanks for looking into this. See the other issue for an example of my "dev" config.

**Comment by neomatrix369** [comment]
Solved during our work on this repo.
